# Generated by Django 4.2.3 on 2024-11-10 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_habitacion",
                    models.CharField(
                        choices=[
                            ("EST", "Estándar"),
                            ("DLX", "Deluxe"),
                            ("VIP", "VIP"),
                            ("SUI", "Suite"),
                        ],
                        max_length=3,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("numero_habitaciones_disponibles", models.IntegerField()),
                ("capacidad", models.IntegerField()),
                (
                    "precio_por_noche",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("descripcion", models.TextField()),
                ("tiene_vista_al_mar", models.BooleanField(default=False)),
                ("tiene_aire_acondicionado", models.BooleanField(default=False)),
                ("tiene_wifi", models.BooleanField(default=True)),
                ("tiene_desayuno_incluido", models.BooleanField(default=False)),
                ("tiene_bano_privado", models.BooleanField(default=True)),
                ("tiene_television", models.BooleanField(default=True)),
                ("tiene_jacuzzi", models.BooleanField(default=False)),
                ("tiene_minibar", models.BooleanField(default=False)),
                ("tiene_servicio_a_habitacion", models.BooleanField(default=True)),
                ("tiene_caja_fuerte", models.BooleanField(default=True)),
                ("tiene_balcón", models.BooleanField(default=False)),
                (
                    "metros_cuadrados",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("tipo_cama", models.CharField(default="Cama doble", max_length=50)),
                ("numero_de_camas", models.IntegerField(default=1)),
                ("admite_mascotas", models.BooleanField(default=False)),
                (
                    "tiene_acceso_para_discapacitados",
                    models.BooleanField(default=False),
                ),
                ("tiene_zona_de_trabajo", models.BooleanField(default=False)),
                ("tiene_sistema_sonido", models.BooleanField(default=False)),
                ("tiene_smart_tv", models.BooleanField(default=False)),
                ("tiene_asistente_virtual", models.BooleanField(default=False)),
                ("tiene_detector_humo", models.BooleanField(default=True)),
                ("tiene_rociadores", models.BooleanField(default=True)),
                ("tiene_sistema_de_seguridad", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotels.hotels"
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "unique_together": {("hotel", "nombre", "tipo_habitacion")},
            },
        ),
    ]
