apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: "db"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"