# microservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
        - name: hotels
          image: knimisica/hotels:latest
          envFrom:
            - configMapRef:
                name: hotels-secret
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: hotels
spec:
  selector:
    app: hotels
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
