# Generated by Django 4.2.3 on 2024-11-10 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0002_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dias_reservados", models.IntegerField()),
                ("usuario", models.PositiveIntegerField()),
                ("pagado", models.BooleanField(default=False)),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotels.rooms"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "unique_together": {("habitacion", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="PaymentsReservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=8)),
                ("id_transaccion", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("metodo_pago", models.CharField(max_length=50)),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="availability.reservations",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de reserva",
                "verbose_name_plural": "Pagos de reservas",
            },
        ),
    ]
