# Generated by Django 4.2.3 on 2024-11-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0002_alter_paymentsreservations_reserva"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservations",
            unique_together=set(),
        ),
    ]
